### ISSUE TITLE
Unit questions in Swerve example

### ISSUE THREAD

**Issue by mdressel** [CrossTheRoadElec/Phoenix6-Examples#30]
It isn't clear what unit this is in TunerConstants.java:119

`private static final double kBackRightEncoderOffset = -0.84130859375;`

If everything else is in meters, should this also be in meters? TunerConstants:122

`private static final double kBackRightYPosInches = -10.5;`

**Comment by jasondaming** [comment]
If you go down to SwerveModuleConstants you can see that it is rotations.  I understand the confusion.
![image](https://github.com/CrossTheRoadElec/Phoenix6-Examples/assets/15695521/ad3dcab3-991c-4f54-b641-d9b43eca0123)

You can see at the bottom of Tuner Constants units are converted from inches to meters.  I think the idea was that many people (american) will know the measurements in inches and are scared of meters.

IMO you are correct and we should do the conversion inline like (and remove the conversion from below):
`private static final double kBackRightYPosInches = Units.inchesToMeters(-10.5);`

This allows units scared of meters to easily fill in inches and meanwhile allows folks that have meters already to just put it in with a double conversion.

**Comment by EddieDL** [comment]
Thanks for the clarification. I made a few updates to my version based on your comments and I think it would be good to change the example. But my issue is resolved.
