### ISSUE TITLE
Is there a suggested procedure to tune the swerve values

### ISSUE THREAD

**Issue by EddieDL** [CrossTheRoadElec/Phoenix6-Examples#34]
A number of the values created by the Swerve Generator say that they should be tuned for the real robot. Some of them are pretty obvious to us as they are similar to what we have done before. Others like `kCoupleRatio`, `kSpeedAt12VoltsMps`, and `kSlipCurrentA` aren't as clear to us. Below are our current assumptions related to these:
- kCoupleRatio: It doesn't seem like we would need to actually tune this if we are running the same modules as were selected in the factory.
- kSpeedAt12VoltsMps: This says it is looking for frees speed, but maybe we are supposed to run the robot at 12volts and capture the speed?
- kSlipCurrentA: We assume we are supposed to put the robot up against a wall and increase current until the wheels slip and capture the max current draw to do so.

Lastly, if we want to switch to `TorqueCurrentFOC` what process is best to tune the PID values? Can we just use the standard process identified in the Pheonix documentation or is there something special to be aware of in the Swerve API?

**Comment by bhall-ctre** [comment]
Most of these are documented in the [Swerve API documentation](https://v6.docs.ctr-electronics.com/en/stable/docs/api-reference/mechanisms/swerve/swerve-builder-api.html#additional-constants).

> kCoupleRatio: It doesn't seem like we would need to actually tune this if we are running the same modules as were selected in the factory.

Correct, if you did not select a "Custom" module type, then the coupling ratio should already be correct.

> kSpeedAt12VoltsMps: This says it is looking for frees speed, but maybe we are supposed to run the robot at 12volts and capture the speed?

kSpeedAt12VoltsMps is the speed of the robot in m/s when driving the robot at a full 12 V. We approximate this in the project generator using the wheel radius and drive gear ratio, but you may want to empirically measure it to account for mechanical losses.

> kSlipCurrentA: We assume we are supposed to put the robot up against a wall and increase current until the wheels slip and capture the max current draw to do so.

Yes.

> Lastly, if we want to switch to TorqueCurrentFOC what process is best to tune the PID values? Can we just use the standard process identified in the Pheonix documentation or is there something special to be aware of in the Swerve API?

Tuning TorqueCurrentFOC is similar to tuning any other closed loop, but there are a couple differences we mention in the [closed-loop docs](https://v6.docs.ctr-electronics.com/en/stable/docs/api-reference/device-specific/talonfx/closed-loop-requests.html#choosing-output-type):
- kV is typically 0 in TorqueCurrentFOC
- kA can be tuned on its own
- Not mentioned in the docs right now: in position-based control modes (including Motion Magic®), you need to tune kD. You should already do this in voltage-based position closed loops, but it's required with TorqueCurrentFOC.

**Comment by EddieDL** [comment]
This makes sense, thank you for the additional context.
