### ISSUE TITLE
Swerve simulation SUPER slow

### ISSUE THREAD

**Issue by EddieDL** [CrossTheRoadElec/Phoenix6-Examples#35]
Is it possible that the default values for 'kSteerInertia`, `kDriveInertia`, `kSteerFrictionVoltage`, and `kDriveFrictionVoltage` are wrong for the MK4i? When we run the example using the simulator the robot moves great. When we run the version we created with the creator it moves correctly but is incredibly slow.

When we look at these values they are the same as the example but it isn't clear what these do or if they could be why the simulation isn't working how we would expect.

**Comment by bhall-ctre** [comment]
Double check your TunerConstants and RobotContainer. We approximate `TunerConstants.kSpeedAt12VoltsMps` in the generated project, so make sure that value looks correct. And RobotContainer contains the swerve control requests, so it's possible that there's a speed cap applied there.

**Comment by EddieDL** [comment]
`kSpeedAt12VoltsMps = 9.46;`

From `Robot Container`. These are direct copies of what was in the example in this repo (though we increased some of the values
```
  private double MaxSpeed = 9; // 6 meters per second desired top speed
  private double MaxAngularRate = 2.5 * Math.PI; // 3/4 of a rotation per second max angular velocity

  private final SwerveRequest.FieldCentric drive = new SwerveRequest.FieldCentric()
      .withDeadband(MaxSpeed * 0.1).withRotationalDeadband(MaxAngularRate * 0.1) // Add a 10% deadband
      .withDriveRequestType(DriveRequestType.OpenLoopVoltage); // I want field-centric
                                                               // driving in open loop
```

Based on everything we see. It should work in simulation, but it does not.

In the "real-world" the robot drives great. We haven't tried auto yet, but overall it is so much less code to deal with :)

**Comment by EddieDL** [comment]
Well we figured out the problem and it was similar to the other issues. It appears that all areas of the API use meters with the exception of "withWheelRadius()" that only accepts inches.
