### ISSUE TITLE
SwerveWithPathPlanner Can't Turn during Simulation

### ISSUE THREAD

**Issue by EvanLuo42** [CrossTheRoadElec/Phoenix6-Examples#36]
We are using the SwerveWithPathPlanner example, and we drew an auto in pathplanner. It looks like this:
<img width="1280" alt="image" src="https://github.com/CrossTheRoadElec/Phoenix6-Examples/assets/62578958/f0a3bbe1-b703-4d99-a21b-cf2931cb0bf3">

However, it can't go in this path. Instead, it only go straight forward:
<img width="998" alt="image" src="https://github.com/CrossTheRoadElec/Phoenix6-Examples/assets/62578958/d67fba38-2950-435a-b60b-04d541c71f33">

There is also CAN bus error saying:
`CAN frame not received/too-stale. Check the CAN bus wiring, CAN bus utilization, and power to the device.
	ctre.phoenix6.BaseStatusSignal.waitForAll`

The `FailedDaqs` is also increasing and `SuccessfulDaqs` is zero.

**Comment by jasondaming** [comment]
Did you make the path on the red side?  Paths should only be made on the blue side per the [PP documentation](https://pathplanner.dev/home.html)

**Comment by EvanLuo42** [comment]
> Did you make the path on the red side? Paths should only be made on the blue side per the [PP documentation](https://pathplanner.dev/home.html).
> 
> If you were trying running on the red side the CTRE example isn't configured for [alliance path swapping](https://github.com/CrossTheRoadElec/Phoenix6-Examples/blob/ca850048fe438b26bb3564a1c089853d09cb9483/java/SwerveWithPathPlanner/src/main/java/frc/robot/CommandSwerveDrivetrain.java#L65). I would recommend looking at my [upgraded version of their example](https://github.com/jasondaming/ctre_swerve/blob/c7ed317169ac27536f44007554dfdf63955f3744/src/main/java/frc/robot/CommandSwerveDrivetrain.java#L65-L74) for this and many other features.

No I have already flip the path and also flipped the start position of odometry. It works well in the real world.

**Comment by jasondaming** [comment]
Then you have made a lot of changes to the example. I think we are going to need to see the code to help further
